# Site
name: 'Air-Banyan (Beta)'
description: 'Embrace sustainable travel with AirBanyan: Your go-to destination for eco-conscious adventures. Explore our blog for inspiring stories, green travel tips, and eco-friendly accommodations. Join the movement towards a greener future and indulge in unforgettable experiences that leave a positive footprint. Start your environmentally responsible journey with AirBanyan today and make a difference with every step you take.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    # sal:
    #   name:           sal
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar1.jpg
    #   bio:            "Hi, I am Harisankar P, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    #   email:          wowthemesnet@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet

    hari:
      name:           Harisankar P
    
      avatar:         'assets/images/avatar1.jpg'
      bio:            "Hi, I am Harisankar P, the author of this blog, I hope you like it!  Reach me on my mail: harisankar@airbanyan.in"
      email:          harisankar@airbanyan.in
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 4



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
